name: CI
on:
  pull_request:
    branches:
      - main
jobs:
  security_hardening:
    name: Check security hardening
    runs-on: ubuntu-latest
    needs: testing
    permissions:
      contents: read
    steps:
      - name: Clone the repository
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # ratchet:actions/checkout@v3.2.0
      - uses: actions/download-artifact@9782bd6a9848b53b110e712e20e42d89988822b7 # ratchet:actions/download-artifact@v3
        with:
          name: dist
      - name: Ensure SHA pinned actions
        uses: ./
  testing:
    name: Run testing
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:
      - name: Clone the repository
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # ratchet:actions/checkout@v3.2.0
      - name: Set Node.js 16.x
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # ratchet:actions/setup-node@v3.5.1
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm ci
      - name: Linter
        run: npm run lint
      - name: Tester
        run: npm run test
      - name: Preparer
        run: npm run prepare
      - uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb # ratchet:actions/upload-artifact@v3
        with:
          name: dist
          path: dist/
          retention-days: 1
      - name: Update dist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr checkout ${{ github.event.pull_request.number }}
          git config --global user.name "action-bot"
          git config --global user.email "action-bot@philips.com"
          DIFF=$(git diff-index HEAD dist/)
          if [ "$DIFF" ]
          then
            echo "Distribution is changed."
          else
            echo "Distribution is up-to-date."
          fi

  update_dist:
    name: Update dist
    runs-on: ubuntu-latest
    needs: testing
    permissions:
      contents: write
      actions: read
    steps:
      - name: Clone the repository
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # ratchet:actions/checkout@v3.2.0
      - run: |
          ls -la
          ls -la dist
      - uses: actions/download-artifact@9782bd6a9848b53b110e712e20e42d89988822b7 # ratchet:actions/download-artifact@v3
        with:
          name: dist
          path: dist/
      - run: |
          ls -la
          ls -la dist
          git status
      - name: Update dist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr checkout ${{ github.event.pull_request.number }}
          git config --global user.name "action-bot"
          git config --global user.email "action-bot@philips.com"
          DIFF=$(git diff-index HEAD dist/)
          if [ "$DIFF" ]
          then
            git add --all dist/
            git commit -m "chore: Update action dist" -m "skip-checks: true" dist/
            git push
          else
            echo "Distribution is up-to-date."
          fi
