name: CI
on:
  pull_request:
    branches:
      - main
jobs:
  security_hardening:
    name: Check security hardening
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # ratchet:actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - name: Ensure SHA pinned actions
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@8877889a5717dad0b139f1d2925689aa68f88a43 # ratchet:zgosalvez/github-actions-ensure-sha-pinned-actions@8877889a5717dad0b139f1d2925689aa68f88a43
  testing:
    name: Run testing
    needs: security_hardening
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # ratchet:actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - name: Set Node.js 16.x
        uses: actions/setup-node@270253e841af726300e85d718a5f606959b2903c # ratchet:actions/setup-node@270253e841af726300e85d718a5f606959b2903c
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm ci
      - name: Linter
        run: npm run lint
      - name: Tester
        run: npm run test
      - name: Preparer
        run: npm run prepare
      - name: Update dist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |-
          gh pr checkout ${{ github.event.pull_request.number }}
          git config --global user.name "action-bot"
          git config --global user.email "action-bot@philips.com"
          DIFF=$(git diff-index HEAD dist/)
          if [ "$DIFF" ]
          then
            git commit -m "chore: Update action dist" dist/index.js
            git push
          else
            echo "Distribution is up-to-date."
          fi
