name: CI
on:
  pull_request:
    branches:
      - main
permissions:
  contents: write
jobs:
  security_hardening:
    name: Check security hardening
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # ratchet:actions/checkout@v3.4.0
      - name: Ensure SHA pinned actions
        uses: ./
  testing:
    name: Run testing
    needs: security_hardening
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # ratchet:actions/checkout@v3.4.0
      - name: Set Node.js 16.x
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # ratchet:actions/setup-node@v3.5.1
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm ci
      - name: Linter
        run: npm run lint
      - name: Tester
        run: npm run test
      - name: Preparer
        run: npm run prepare
      - name: Update dist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr checkout ${{ github.event.pull_request.number }}
          git config --global user.name "action-bot"
          git config --global user.email "action-bot@philips.com"
          DIFF=$(git diff-index HEAD dist/)
          if [ "$DIFF" ]
          then
            git commit -m "chore: Update action dist" dist/index.js
            git push
          else
            echo "Distribution is up-to-date."
          fi
