name: Release
on:
  push:
    branches:
      - main
permissions:
  contents: read
  issues: write
  pull-requests: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Get app installation token
        uses: philips-software/app-token-action@a37926571e4cec6f219e06727136efdd073d8657 # ratchet:philips-software/app-token-action@v1.1.2
        id: token
        with:
          app_id: ${{ secrets.RELEASE_BOT_APP_ID }}
          app_base64_private_key: ${{ secrets.RELEASE_BOT_APP_PRIVATE_KEY_BASE64 }}
          auth_type: installation
      - name: Release
        uses: google-github-actions/release-please-action@51ee8ae2605bd5ce1cfdcc5938684908f1cd9f69 # ratchet:google-github-actions/release-please-action@v3.7.9
        with:
          release-type: simple
          token: ${{ steps.token.outputs.token }}
