name: "Semantic Check"
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
permissions:
  contents: read
  pull-requests: read
jobs:
  main:
    name: Semantic Commit Message Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # ratchet:actions/checkout@v3.2.0
      - uses: amannn/action-semantic-pull-request@c3cd5d1ea3580753008872425915e343e351ab54 # ratchet:amannn/action-semantic-pull-request@v5.2.0
        name: Check PR for Semantic Commit Message
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          requireScope: false
