name: "Semantic Check"
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
permissions:
  contents: read
  pull-requests: read
jobs:
  main:
    name: Semantic Commit Message Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # ratchet:actions/checkout@v3.5.0
      - uses: amannn/action-semantic-pull-request@570204e54c9030a6cb7ef781c492e76c1798d1c0 # ratchet:amannn/action-semantic-pull-request@v5.0.1
        name: Check PR for Semantic Commit Message
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          requireScope: false
